Repository Infumia/InfumiaLib, pull requests merged in 2021-07, with the labels that each got.

#169 development.
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/Builder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/SkullItemBuilder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/element/FileElement.java
Labels: automerge, release/patch

#168 Update LuckPermsWrapper and GroupManagerWrapper
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/Groups.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/GroupManagerWrapper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/LuckPermsWrapper.java
Labels: automerge, release/patch

#170 Update publish.yml
  .github/workflows/publish.yml
Labels: automerge, release/patch

#171 Dev
  .github/workflows/build.yml
  paper/pom.xml
  paper/src/main/java/tr/com/infumia/infumialib/paper/InfumiaLib.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/location/Cuboid.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/AbstractWorldBorder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/ConsumerSupplierTupel.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/FunctionDoubleDoubleLong.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/IWorldBorder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/PersistentWorldBorderApi.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/Position.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/WorldBorderAction.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/WorldBorderApi.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/WorldBorderApiImpl.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/api/WorldBorderData.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/plugin/PersistenceWrapper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/plugin/WorldBorderDataTagType.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/v1_16/Border.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/com/github/yannicklamprecht/worldborder/v1_16/WorldBorder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/shade/package-info.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/util/SlotPos.java
Labels: automerge, release/patch

#174 Dev
  common/pom.xml
  paper/src/main/java/tr/com/infumia/infumialib/paper/location/Cuboid.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/util/SlotPos.java
Labels: automerge, release/patch

#175 Dev
  common/src/main/java/tr/com/infumia/infumialib/replaceable/RpBase.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/InfumiaLib.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/files/PaperConfig.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/pl3xmap/MapTask.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/serializers/SentTitle.java
Labels: automerge, release/patch

#176 delegate.
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/VaultWrapper.java
Labels: automerge, release/patch

#179 Update Page.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/Page.java
Labels: automerge, release/patch

#180 add sent title object to store it in mongo
  paper/src/main/java/tr/com/infumia/infumialib/paper/mongodb/SentTitleObject.java
Labels: automerge, release/patch

#183 add to string, equals, hashcode methods for sent title.
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitSimpleJson.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/serializers/SentTitle.java
Labels: automerge, release/patch

#184 Dev
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/util/SlotPos.java
Labels: automerge, release/patch

#185 make it accessible.
  paper/src/main/java/tr/com/infumia/infumialib/paper/listeners/ListenerHandler.java
Labels: automerge, release/patch

#186 add new useful methods for sent title.
  common/src/main/java/tr/com/infumia/infumialib/transformer/TransformResolver.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/resolvers/WrappedTransformResolver.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/color/CustomColors.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/serializers/SentTitle.java
Labels: automerge, release/patch

#188 revert
  common/src/main/java/tr/com/infumia/infumialib/maps/MutableMap.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/TransformResolver.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/resolvers/WrappedTransformResolver.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/SmartHolder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/holder/SmartInventoryHolder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/page/BasicPage.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitSimpleJson.java
Labels: automerge, release/patch

#189 Update InventoryContents.java
  common/src/main/java/tr/com/infumia/infumialib/input/ChatInput.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/TransformedObject.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/postprocessor/PostProcessor.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/location/Cuboid.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/InventoryContents.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/serializers/SentTitle.java
Labels: automerge, release/patch

#191 remove streams.
  common/src/main/java/tr/com/infumia/infumialib/element/Placeholder.java
  common/src/main/java/tr/com/infumia/infumialib/reflection/RefClass.java
  common/src/main/java/tr/com/infumia/infumialib/reflection/clazz/ClassOf.java
  common/src/main/java/tr/com/infumia/infumialib/replaceable/RpBase.java
  common/src/main/java/tr/com/infumia/infumialib/replaceable/RpList.java
  common/src/main/java/tr/com/infumia/infumialib/scoreboard/Board.java
  common/src/main/java/tr/com/infumia/infumialib/scoreboard/line/Line.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/TransformRegistry.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/TransformResolver.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/TransformedObject.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/declarations/GenericDeclaration.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/declarations/TransformedObjectDeclaration.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/resolvers/Hocon.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/transformers/TransformerStringListToRpList.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/Buildable.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/Builder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/FireworkItemBuilder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/PotionItemBuilder.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/color/XColor.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/element/PlaceType.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/Groups.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/LuckPermsWrapper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/PermissionsExWrapper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/pl3xmap/MapTask.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/pl3xmap/Pl3xMapWrapper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/scoreboard/BukkitScoreboardSender.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/SmartInventory.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/handle/BasicHandle.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/icon/BasicIcon.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/page/BasicPage.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitGsonJson.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitHJsonJson.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitHocon.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitJacksonJson.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitJacksonYaml.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitResolverHelper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitSimpleJson.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/resolvers/BukkitSnakeyaml.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/utils/RunnableWrapper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/utils/TaskUtilities.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/versionmatched/VersionMatched.java
Labels: automerge, release/patch

#194 Update Times.java
  common/src/main/java/tr/com/infumia/infumialib/time/Times.java
Labels: automerge, release/patch

#195 Dev
  .github/dependabot.yml
  .github/workflows/build.yml
  common/pom.xml
  paper/pom.xml
  pom.xml
  velocity/pom.xml
Labels: automerge, release/patch

#199 Update TransformResolver.java
  common/src/main/java/tr/com/infumia/infumialib/transformer/TransformResolver.java
Labels: automerge, release/patch

#200 add useful methods for SentTitle class.
  paper/src/main/java/tr/com/infumia/infumialib/paper/commands/InfumiaPluginCommands.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/Page.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/SmartInventory.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/event/IcClickEvent.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/event/IcDragEvent.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/event/PgBottomClickEvent.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/event/PgClickEvent.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/event/PgOpenEvent.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/event/PgOutsideClickEvent.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/event/abs/CloseEvent.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/listener/InventoryClickListener.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/listener/InventoryCloseListener.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/listener/InventoryDragListener.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/listener/InventoryOpenListener.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/listener/PlayerQuitListener.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/listener/PluginDisableListener.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/page/BasicPage.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/transformer/serializers/SentTitle.java
Labels: automerge, release/patch

#201 development.
  common/src/main/java/tr/com/infumia/infumialib/replaceable/RpBase.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/InfumiaLib.java
Labels: automerge

#202 development.
  paper/src/main/java/tr/com/infumia/infumialib/paper/smartinventory/InventoryContents.java
Labels: automerge, release/patch

#205 add addLore setLore setName methods with Component.
  .github/workflows/publish.yml
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/Buildable.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/bukkititembuilder/Builder.java
Labels: automerge, release/minor

#206 Dev
  paper/pom.xml
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/Groups.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/Hooks.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/GroupManagerHook.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/GroupManagerWrapper.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/PermissionsExHook.java
  paper/src/main/java/tr/com/infumia/infumialib/paper/hooks/hooks/PermissionsExWrapper.java
  pom.xml
Labels: automerge, release/patch

#208 Update jitpack.yml
  jitpack.yml
Labels: automerge, release/patch

#209 Update jitpack.yml
  jitpack.yml
Labels: automerge, release/patch
